name: Deploy AWS Lab Playground

on:
  push:
    branches: [ main-clean ]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push Docker image
        run: |
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:dev-${GITHUB_SHA::7}
          docker build -t $IMAGE_URI ./docker
          docker push $IMAGE_URI
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      - name: Terraform Init
        working-directory: ./
        run: |
          terraform init -backend-config="environments/development/backend.hcl"

      - name: Terraform Plan
        working-directory: ./
        run: |
          terraform plan \
            -var-file="environments/development/terraform.tfvars" \
            -var "docker_image=${IMAGE_URI}" \
            -out=tfplan-dev

      - name: Terraform Apply
        working-directory: ./
        run: terraform apply -auto-approve tfplan-dev
